controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
api_login_check:
    path: /api/login

api_refresh_token:
    path: /api/refresh/token